# Generated by Django 5.1.4 on 2025-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_accounts_user_is_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_operator',
            new_name='is_doctor',
        ),
    ]
