# Generated by Django 5.1.4 on 2025-03-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_is_operator_user_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Pharmassist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_labbotomist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
