# Generated by Django 5.1.4 on 2025-03-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Pharmassist',
            new_name='is_pharmassist',
        ),
    ]
