# Generated by Django 5.1.4 on 2025-02-07 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='doctor_images/')),
                ('address', models.CharField(max_length=120)),
                ('mobile_no', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('remark', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
