# Generated by Django 5.1.4 on 2025-03-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_test_b2b_max_price_alter_test_b2b_min_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='remark',
            new_name='description',
        ),
    ]
