# Generated by Django 5.1.4 on 2025-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_home_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
