# Generated by Django 5.1.4 on 2025-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_remove_home_banner_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(default='sdsd', max_length=120),
            preserve_default=False,
        ),
    ]
