# Generated by Django 5.1.4 on 2025-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_lab_lab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.EmailField(default=True, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
