# Generated by Django 5.1.4 on 2025-03-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_remove_lab_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='address',
            field=models.TextField(default='sdsd'),
            preserve_default=False,
        ),
    ]
