# Generated by Django 5.1.4 on 2025-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_test_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='address',
        ),
        migrations.AddField(
            model_name='lab',
            name='address',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
