# Generated by Django 5.1.4 on 2025-03-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_test_category_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
