# Generated by Django 5.1.4 on 2025-03-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='email',
        ),
    ]
