# Generated by Django 5.1.4 on 2025-03-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0010_remove_test_price_test_b2b_max_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_time', models.IntegerField()),
                ('b2b_price', models.IntegerField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.lab')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.test')),
            ],
        ),
    ]
