# Generated by Django 5.1.4 on 2025-03-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
