# Generated by Django 5.1.4 on 2025-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_rename_phone_number_labbotomist_details_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbotomist_details',
            name='email',
            field=models.EmailField(default='ASAS@G.COM', max_length=255),
            preserve_default=False,
        ),
    ]
