# Generated by Django 5.1.4 on 2025-03-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labbotomist_details_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbotomist_details',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
