# Generated by Django 5.1.4 on 2025-03-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_labbotomist_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbotomist_details',
            name='only_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
