# Generated by Django 5.1.4 on 2025-03-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_labbotomist_details_only_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbotomist_details',
            name='email',
        ),
    ]
