# Generated by Django 5.1.4 on 2025-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_remove_labbotomist_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_test',
            name='address',
            field=models.TextField(default='asas'),
            preserve_default=False,
        ),
    ]
