# Generated by Django 5.1.4 on 2025-03-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_lab_test_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_test',
            name='address',
        ),
    ]
