# Generated by Django 5.1.4 on 2025-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_test_order_lab_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected_from_customer', 'Collected From Customer'), ('delivered_to_hub', 'Delivered To Hub'), ('collected_from_vendor', 'Collected From Vendor'), ('delivered_to_vendor', 'delivered_to_vendor'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
