# Generated by Django 5.1.4 on 2025-03-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_is_labitnow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_labitnow',
            field=models.BooleanField(default=False),
        ),
    ]
